# wrangler.toml
name = "DigitalMarketingAgency"
compatibility_date = "2024-02-09"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[build.upload]
format = "service-worker"

[site]
bucket = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18"